Hw02 fix app
nickmelekh/home_work_basic pull request #1
Opened 2024-03-18 09:55 UTC by nickmelekh

## Домашнее задание №2 «Чиним, собираем и запускаем приложение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Приложение локально собирается
- [ ] Линтер не выдает ошибок при локальном запуске

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла

#### Зачёт от 4 баллов

2024-03-18 12:09 UTC, vladislavmass requested changes
Хорошее начало, но есть несколько замечаний по коду, а также необходимо внести правки в имя модуля в файле go.mod

2024-03-18 12:09 UTC, vladislavmass commented on hw02_fix_app/printer/pkg.go
>  		fmt.Println(str)
Тут хватило бы `fmt.Println(staff[i])`

2024-03-18 12:09 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		fmt.Printf("Error: %v", err)
Если произошла ошибка, то нужно ее вернуть. `return nil,err`

2024-03-18 12:09 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  		return nil, nil
Если произошла ошибка, то нужно ее вернуть. `return nil,err`

2024-03-18 12:09 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
> +		return nil, nil
Если произошла ошибка, то нужно ее вернуть. `return nil,err`

2024-03-18 12:09 UTC, vladislavmass commented on hw02_fix_app/reader/pkg.go
>  	res := data
В этой строчке нет никакого смысла

2024-03-18 12:49 UTC, nickmelekh commented
исправил

2024-03-18 14:30 UTC, vladislavmass requested changes

2024-03-18 14:30 UTC, vladislavmass commented on hw02_fix_app/go.mod
>  module github.com/fixme_my_friend/hw02_fix_app
Неверное имя модуля

2024-03-18 15:50 UTC, nickmelekh commented on hw02_fix_app/go.mod
>  module github.com/fixme_my_friend/hw02_fix_app
Понял, исправил

2024-03-19 16:31 UTC, vladislavmass approved these changes

2024-03-20 09:35 UTC, merged